# Generated by Django 4.1.7 on 2023-08-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("raaznotes", "0002_alter_post_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("cover_url", models.URLField()),
                ("tags", models.CharField(max_length=100)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
